---
title: Assignment 04
author: Alex Stout and Rachel Schneider
format: html
---

Data: https://www.pewresearch.org/politics/dataset/2014-political-polarization-survey/ 

```{r warning = FALSE, message = FALSE}
library(haven)
library(ggplot2)
library(dplyr)

# Load Data
data <- read_sav("/Users/alexstout/Desktop/DataScience/assignment04/data/polarization_2014_public.sav")

# Bar Chart

# Select columns and remove missing values
count_data <- data %>%
  select(qb12) %>%
  na.omit()

# Count the number of respondents by answer to qb12
count_data <- count_data %>%
  group_by(qb12) %>%
  summarize(count = n())

# Calculate the percentage of respondents by party and ideology
percent_data <- count_data %>%
  group_by(qb12) %>%
  mutate(percent = count/3135*100)

# Create bar chart
ggplot(subset(percent_data, qb12 <= 2), aes(x = qb12, y = percent, fill = factor(qb12))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Desire for Bipartisan Collaboration") +
  xlab("Should the politicians who share your views work with politicians they disagree with?") +
  ylab("Pecernt of Respondents") +
  scale_x_continuous(
    breaks = c(1, 2),
    labels = c("Work together", "Stand up for positions")
  ) +
  scale_fill_manual(values = c("#00569B", "#80B6D1")) +
  theme_minimal() +
  guides(fill = FALSE)
```

```{r warning = FALSE, message = FALSE}
library(ggplot2)
library(ggpubr)
theme_set(theme_pubr())

# Create visualization

data("data")

# create balloon chart

# Select columns and remove missing values
count_dataq5 <- data %>%
  select(qb5, usr) %>% filter(usr == "U" | usr == "S" | usr == "R") %>%
  na.omit()

# Count the number of respondents by answer to qb5
count_dataq5 <- count_dataq5 %>%
  group_by(qb5, usr) %>%
  summarize(count = n())

# Create a scatter plot with circle size proportional to count
cdat_sp <- ggplot(subset(count_dataq5, qb5 <= 3), aes(x = factor(usr), y = factor(qb5), size = count)) +
  geom_point(shape = 21, colour = "black", fill = "light blue")

# Set the factor levels to include in the x-axis
usr_levels <- c("U", "S", "R")

# Set the factor levels to include in the y-axis
qb5_levels <- c(1:3)

# map to area and make circles larger
cdat_sp + scale_size_area(max_size = 20) +
  labs(title = "View of level of differnce between parties by voter residential demographic") +
  scale_x_discrete(limits = usr_levels, expand = c(0.25, 0.25), labels = c("urban", "suburban", "rural")) +
  scale_y_discrete(limits = qb5_levels, expand = c(0.25, 0.25), labels = c("a great deal", "a fair amount","hardly any")) +
  labs(x = "voter type", y = "difference between democratic and republican parties")
```
```{r warning = FALSE, message = FALSE}
library(ggplot2)
library(dplyr)
library(sf)
library(tigris) 
library(stringr)

# Creating the Map of the US

map <- tigris:: states(cb = TRUE, progress_bar = FALSE) %>%
  filter(!STATEFP %in% c("78", "69", "66", "60", "72", "02", "15"))

map %>%
  ggplot() + 
  geom_sf() + 
  theme_void()

# Cleaning and Combining Data

(vis01 <- Polarization_2014_public %>%
    filter(qb2 != 9, !is.na(qb2))%>%
    mutate(state = str_pad(state, side = "left", pad = "0", width = 2)) %>%
    select(state, respid, qb2) %>%
    rename(STATEFP = state) %>%
    group_by(STATEFP, qb2) %>%
    summarize(qb_count = n())
)

(state_total <- Polarization_2014_public %>%
    filter(qb2 != 9, !is.na(qb2))%>%
    mutate(state = str_pad(state, side = "left", pad = "0", width = 2)) %>%
    select(state, respid, qb2) %>%
    rename(STATEFP = state) %>%
    group_by(STATEFP) %>%
    summarize(state_count = n())
)

(vis01 <- left_join(state_total, vis01, by = "STATEFP") %>%
  mutate(percent = qb_count/state_count) %>%
    filter(qb2 != 2)
)

(vis01 <- left_join(map, vis01, by = "STATEFP"))

## Creating the Choropleth

(vis01 %>%  
  ggplot() +
  geom_sf(aes( 
    fill = percent)) + 
  scale_fill_gradient(
    low = "#cfe8f3",
    high = "#062635",
    labels = scales :: percent) + 
  theme_void() + 
  labs(
    title = "Satisfaction in the United States",
    caption = "Level of satisfaction with the political state of America",
    fill = "Percent Satisfied")
)

```